### ISSUE TITLE
Meh... Make it multi-platform and without using helper scripts or GTFO

### ISSUE THREAD

**Issue by int3l** [caseykneale/VIMKiller#10]
Title says it all - you are being lazy at the moment.
You did the easy hardware part and butchered the software part!
Unacceptable :)

**Comment by arkku** [comment]
Yes, I this is problematic in that it requires installing the helper script, which might not be possible under all circumstances if Vim has already been opened and there is no alternate console available.

One option would be to emulate a USB keyboard and send the keyboard commands to exit Vim. However, this is problematic due to different keyboard layouts, but that could be selectable on the device by means of DIP switches or such.

**Comment by wkeifenheim** [comment]
What about a deluxe version that attaches to a real keyboard, and uses solenoids to press the keys?

**Comment by int3l** [comment]
The issue was just a joke. Thanks for the meme and good luck with the project! :)
